// Set up DOM elements
export const movieBox = document.querySelector("#movie-box");
export const searchInput = document.querySelector("#search");
export const homeButton = document.querySelector("#home-button");
// const popularButton = document.querySelector("#popular-button");
export const topRatedButton = document.querySelector("#top-rated-button");
export const upcomingButton = document.querySelector("#upcoming-button");
export const enterButton = document.querySelector("#enter-button");
export const welcomeScreen = document.querySelector(".welcome-screen");
export const main = document.querySelector(".main");
